"""Isolated research support with no strategy-selection policy."""

from ftmoquant.research.eurusd_tsm_spec import (
    EURUSD_TSM_SEMANTIC_SHA256,
    EURUSD_TSM_SPEC_PATH,
    EurusdTsmSpec,
    EurusdTsmSpecError,
    load_eurusd_tsm_spec,
    semantic_sha256_for_document,
)
from ftmoquant.research.experiment_spec import (
    REGISTRY_COLUMNS,
    ExperimentRegistryEntry,
    ExperimentRegistryValidationError,
    StrategySpecValidationError,
    TrendPullbackSpec,
    canonical_spec_json,
    load_experiment_registry,
    load_trend_pullback_spec,
    strategy_config_sha256,
)
from ftmoquant.research.liquidity_shock_reversion_spec import (
    LIQUIDITY_SHOCK_REVERSION_CONFIG_SHA256,
    LIQUIDITY_SHOCK_REVERSION_SPEC_PATH,
    LiquidityShockReversionSpec,
    LiquidityShockReversionSpecValidationError,
    liquidity_shock_reversion_config_sha256,
    load_liquidity_shock_reversion_spec,
)
from ftmoquant.research.session_range_expansion_spec import (
    SESSION_RANGE_EXPANSION_CONFIG_SHA256,
    SESSION_RANGE_EXPANSION_SPEC_PATH,
    SessionRangeExpansionSpec,
    SessionRangeExpansionSpecValidationError,
    load_session_range_expansion_spec,
    session_range_expansion_config_sha256,
)
from ftmoquant.research.ts_momentum_spec import (
    TS_MOMENTUM_CONFIG_SHA256,
    TS_MOMENTUM_SPEC_PATH,
    TsMomentumSpec,
    TsMomentumSpecValidationError,
    load_ts_momentum_spec,
    ts_momentum_config_sha256,
)

__all__ = [
    "EURUSD_TSM_SEMANTIC_SHA256",
    "EURUSD_TSM_SPEC_PATH",
    "EurusdTsmSpec",
    "EurusdTsmSpecError",
    "REGISTRY_COLUMNS",
    "ExperimentRegistryEntry",
    "ExperimentRegistryValidationError",
    "StrategySpecValidationError",
    "TrendPullbackSpec",
    "TS_MOMENTUM_CONFIG_SHA256",
    "TS_MOMENTUM_SPEC_PATH",
    "TsMomentumSpec",
    "TsMomentumSpecValidationError",
    "canonical_spec_json",
    "load_experiment_registry",
    "load_eurusd_tsm_spec",
    "load_trend_pullback_spec",
    "load_ts_momentum_spec",
    "strategy_config_sha256",
    "semantic_sha256_for_document",
    "ts_momentum_config_sha256",
    "SESSION_RANGE_EXPANSION_CONFIG_SHA256",
    "SESSION_RANGE_EXPANSION_SPEC_PATH",
    "SessionRangeExpansionSpec",
    "SessionRangeExpansionSpecValidationError",
    "load_session_range_expansion_spec",
    "session_range_expansion_config_sha256",
    "LIQUIDITY_SHOCK_REVERSION_CONFIG_SHA256",
    "LIQUIDITY_SHOCK_REVERSION_SPEC_PATH",
    "LiquidityShockReversionSpec",
    "LiquidityShockReversionSpecValidationError",
    "liquidity_shock_reversion_config_sha256",
    "load_liquidity_shock_reversion_spec",
]
